name: Node.js builds

on:
  push:
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+.[0-9]+\-test
      - v?[0-9]+.[0-9]+.[0-9]+\-test
      - v?[0-9]+.[0-9]+\-test

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Create release
      env:
        GH_TOKEN: ${{secrets.RELEASE_TOKEN}}
      run: |
        REF=${{github.ref}}
        TAG=${REF#"refs/tags/"}
        gh release create -t "Release ${TAG}" -n "" "${{github.ref}}"
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19
    - name: Install the package
      env:
        DEVELOPMENT_SKIP_GETTING_ASSET: true
      run: |
        npm i
    - name: Save to GitHub
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: npm run save-to-github
